version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.8
  pre_build:
    commands:
      - echo Build started on `date`
build:
    commands:
- echo Building the Docker image...
- docker build
      post_build:
        commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...